
containerized: "container/assemblySC.sif"

include: "rules/common.smk"

include: "rules/readQC.smk"

include: "rules/assemble.smk"

include: "rules/circularize.smk"

if config["annotate"] == "Yes":
    include: "rules/annotate.smk"

include: "rules/summarize.smk"

include: "rules/mapreads.smk"

if config["annotate"] == "Yes":
    rule all:
        input:
            config["outdir"] + "/read_summaries.tsv",
            config["outdir"] + "/assembly_summaries.tsv", 
            expand(config["outdir"] + "/{sample}/bakta/{sample}.gff3", sample = samples.keys()),
            expand(config["outdir"] + "/{sample}/remapping/longreads.bam", sample = samples.keys())

else:
    rule all:
        input:
            config["outdir"] + "/read_summaries.tsv",
            config["outdir"] + "/assembly_summaries.tsv", 
            expand(config["outdir"] + "/{sample}/remapping/longreads.bam", sample = samples.keys())
