##############################
#
##############################

samples: config/samples.tsv
outdir: ./results
output_prefix: pb_bernese

ref:
  genome_size: 4.4m
  gbf: resources/H37Rv.gbf

bakta_db: resources/bakta_db
container: container/assemblySC.sif

threads_per_job: 4

keep_intermediate: "Yes"
