cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=assemblySMK-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.stdout
    --error=logs/{rule}/{rule}-{wildcards}-%j.stderr
default-resources:
  - "partition=scicore"
  - "qos='1day'"
  - "time='12:00:00'"
  - "mem_mb=20000"
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 10
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True


# https://github.com/jdblischak/smk-simple-slurm
